### ISSUE TITLE
Improve 'wash ls'

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#284]
We should make it something you want to use in-place of 'ls' because it provides useful context.

**Comment by grimradical** [comment]
Output ideas:

We could still default a long listing, but use a modeline of sorts to display which protocols are supported by each line item:

```
# wash ls 
d--- 23 May 18:02 foo
-rs- 23 May 18:02 logfile
d--x 23 May 18:02 ssh.mydomain.com
```

Where the modeline refers to:

```
<list?><read?><stream?><exec?> <ctime> <name>
```

This would probably look a lot better with color, a la how [exa](https://the.exa.website/) does it.

**Comment by ekinanp** [comment]
Think we should also omit `.` unless the user wants to list hidden directories. That makes it a bit more consistent with the built-in `ls`.

**Comment by ekinanp** [comment]
I'm starting to think we should keep its default output symmetric with `ls`, and make the current info we show optional (maybe match it with whatever option `ls` has for that behavior?). This would let us directly alias `list` => `ls`, and it also means I can use our `list` in the screencast instead of `ls` (I think the current state of our `list` is a bit too verbose for a tutorial).
