### ISSUE TITLE
When I start Wash, it asks for an MFA token 27 times

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#317]
I'm trying to use Wash and have a bunch of profiles configured that require MFA tokens (tied to the same account, so they re-use the MFA). It's both inconvenient and time-consuming to log into all of them at once.

I also don't use most of them from day-to-day. I'd like some way to choose to log into only a few profiles.

**Comment by ekinanp** [comment]
Since there's also some MFA-related stuff with Kube (via https://github.com/puppetlabs/wash/issues/297) and since we'll likely have auth-related stuff with other cloud providers (e.g. Azure, Vmware), it might be a good time to properly (and generically) handle the pattern of `"I want to do something w/ entry" => "Am I authorized to do it? If no, ask for input. If yes, go ahead" => "Authentication succeeded, can do this thing! Hopefully Wash caches my credentials so I don't have to keep entering that info"`.

**Comment by MikaelSmith** [comment]
Plugin-specific config is already an issue at #289.
