### ISSUE TITLE
Ctrl + C'ing a command kills wash

### ISSUE THREAD

**Issue by genebean** [puppetlabs/wash#329]
**Describe the bug**
Killing the command wash is currently executing kicks me out of the wash shell all together.

**To Reproduce**
1. deploy a single telegraf container to k8s (I am using a deployment)
2. cd into `kubernetes/<cluster>/<namespace>/pods`
3. Run `exec ./<pod name> ls /bin/`
4. See error `./<pod name>: line 1: 2019-06-12T20:37:00Z: command not found` repeated over and over again
5. Press Ctrl + c to kill the exec
6. exec stops but so does the entire wash shell session

**Expected behavior**
Only the exec should be killed, not the entire shell.

**Environment (please complete the following information):**
 - OS: macOS 10.14.5
 - Version/Build number: wash version 0.4.0
 - Cloud target: k8s pod in GKE

**Additional context**
My local shell is zsh and I am using iTerm2.

**Comment by MikaelSmith** [comment]
Are you running `exec` or `wexec`?

**Comment by MikaelSmith** [comment]
Oh, pretty sure exec. It tries to invoke `./<pod name>` as a script because it's a readable file. And it's doing exec, which replaces the shell invocation.

We made some choices around not overriding existing shell functions, but they may not have been the right choices. `exec` seems like it could be particularly confusing because it behaves so differently.

**Comment by MikaelSmith** [comment]
The surprising thing to me is that `exec` doesn't just error out. When I try that on a normal file it gets
```
bash: /Users/michaelsmith/foo: Permission denied
bash: exec: /Users/michaelsmith/foo: cannot execute: Undefined error: 0
```
because the file doesn't have the executable permission. The pod doesn't seem to have the executable permission either, but still executes it. This may be a FUSE thing. I wonder if we should mount with `noexec`.

I believe this immediate behavior will be avoided by #203 and #228. I think there's an open question about confusion between the exec shell built-in and wash exec.

**Comment by genebean** [comment]
interesting... should I be using wexec instead? If so, maybe the built in help could be updated to indicate that there are good reasons to use the w versions of commands

**Comment by MikaelSmith** [comment]
Yeah. I can see how help is confusing there. We'll work on how to make it clearer.
