### ISSUE TITLE
Size attribute must be returned when listing entries in an external script

### ISSUE THREAD

**Issue by binford2k** [puppetlabs/wash#355]
If your external script `list` handler doesn't return a size, it defaults to `0`. The symptom of that is the `ls -l` output showing the zero-byte file. When you later try to `read` the file (eg, by using `cat`) then your script is invoked and returns content and the proper exit code, but the shell doesn't display anything on stdout.

The first problem is that this doesn't appear to be documented.

The second problem is that calculating an accurate size is often expensive, and it would be nice to not need it. (I can see that breaking a lot of assumptions in other tooling, so maybe that suggestion is not a good one.)

```
[~]$ wash --version
wash version 0.4.0
```

**Comment by MikaelSmith** [comment]
What if we put 4k as a default for files that don't provide size, then if they have cached Open results we can use that to determine size instead.

**Comment by binford2k** [comment]
That seems like a reasonable solution. 4k is a pretty common default filesystem block size.

**Comment by MikaelSmith** [comment]
My plan for this ticket is - when there's no size given - first check whether we have content locally cached. If so, use it to figure out the size. Otherwise use a default of 4k as something that's likely not to break existing tools while telling them they should try to read the file.

We should update some existing operations that currently download content to determine the size even if we're not reading it so that they perform better when listing them.
