### ISSUE TITLE
Website Usability Improvements

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#648]
There seems to be a large mismatch between number of people who visit the Wash site and installing page and those who download and try it. Try a new main site oriented at asking people to download Wash, and other improvements.

**Comment by ekinanp** [comment]
Tasks:

[] Update install instructions to mention `wash --verify-install`
[] Add https://github.com/osxfuse/osxfuse/issues/437 to the existing list of known issues. I ran into this when I tried to run Wash on my (newly-imaged) laptop.
[] Add a "Spread the word!" message to contributing. Re-organize contributing so the "really easy stuff" comes first.
[] Separate "feature-oriented" blog posts/screencasts from the "News" section, i.e. have a way to document blog posts that demonstrate Wash than the stuff that's in "News". These should persist.
[] Make the tutorials less intimidating. This could be changing "Tutorial" => "Hands on Wash", and moving the exercises over to a separate page.
[] Spice up the intro! Have a link that points to the installation page, and look into adding an embedded shell that people could use to play around with Wash. This could even replace some of the tutorials/make them more flexible because we can include other core plugins.
