### ISSUE TITLE
Prototype Resource Query API (/find)

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash#683]
Add a `/find` endpoint that implements selecting a set of entries based on a predicate query language. This should become the intermediate format used to implement queries from the `find` command, with predicate matching moved to the server.

Detailed spec to be added later.

**Comment by ekinanp** [comment]
Future work could remove `fullmeta` and have the schema figure out which metadata to use. For example, given something like

```
find -m .tags
```

we'd get `tags` as the parsed key. Logic would then be:

* If `tags` is valid key sequence in partial metadata schema, then use that. Otherwise, if `tags` is a valid key sequence in full metadata schema, use that. Otherwise, it is an invalid key sequence.

**Comment by ekinanp** [comment]
We'll also need to document this stuff on the website, least the RQL grammar in detail.
